# NumPy

##### NumPy is a Linear Algebra Library for Python

# numpy arrays

In [1]:
import numpy as np

In [2]:
list_item = [1,2,3,4]
arr = np.array(list_item)
print(arr)

[1 2 3 4]


In [3]:
print(arr[2])

3


In [4]:
list_mat = [[1,2,3], [4,5,6], [7,8,9]]
np.array(list_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
mat = np.array(list_mat)

In [6]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### numpy range function (0-99) not including 100

In [7]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(0,100,5) # (start, end, stepsize)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((4,5)) # (rows, columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,100) # (start, end, evenly spaced points)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### one dimentional random samples from uniform distribution over 0 to 1

In [14]:
np.random.rand(5)

array([0.51252008, 0.58880669, 0.79613742, 0.28925667, 0.0300128 ])

### two dimentional random samples from uniform distribution over 0 to 1

In [15]:
np.random.rand(5,5)

array([[0.00399388, 0.96387961, 0.40404765, 0.78535687, 0.89666271],
       [0.95512467, 0.74517974, 0.11146096, 0.6050239 , 0.19058419],
       [0.03359037, 0.10858592, 0.73332405, 0.54189304, 0.98394026],
       [0.84930343, 0.8164728 , 0.85883544, 0.25256248, 0.70963282],
       [0.83985824, 0.05504984, 0.64512118, 0.01400288, 0.35713592]])

### random samples from standard normal distribution

In [16]:
np.random.randn(5)

array([-1.38973616, -1.00966313, -0.58380064, -0.27891482,  1.51982616])

In [17]:
np.random.randn(6,5)

array([[-0.98275415, -0.66472229, -1.93243124, -1.75302511,  0.41487731],
       [ 0.9518623 ,  1.14161985,  1.21571595,  0.93999995,  1.27090027],
       [ 1.0011021 , -0.36844203, -1.17562504, -0.55453488, -1.04122184],
       [ 1.41754077,  0.46018901, -1.39485857, -0.30375372, -0.33965996],
       [ 0.74758138, -0.94168576, -0.4964784 , -1.38336024, -0.03072834],
       [-1.35775415,  0.32831193,  0.43469716, -0.55419983,  0.77660205]])

### generate random number

In [18]:
np.random.randint(1, 1000)

210

In [19]:
np.random.randint(1, 1000, 50) # (low, high, size)

array([144, 877, 680, 843, 877, 949, 408, 309, 790, 206, 456, 250,  17,
       977, 678, 777, 878, 980, 673, 483, 933, 748, 940, 226,  28,  42,
       943, 338, 252, 516, 316, 808, 359, 314,  26, 711, 943, 985, 410,
       906, 490,  79, 811, 612, 454, 972, 189, 850,  89, 366])

### reshape elements

In [20]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.shape # indicates one dimentional array

(25,)

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr1 = arr.reshape(5,5) # number of element must be equal to matrix
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr1.shape # indicates two dimentional array

(5, 5)

In [25]:
arr1.dtype

dtype('int32')

### find max and min value in an array

In [26]:
ranarr = np.random.randint(1,55, 10)
ranarr

array([11, 14, 40, 13, 26, 41, 40, 46,  1, 40])

In [27]:
ranarr.dtype

dtype('int32')

In [28]:
ranarr.max() # max value in the array

46

In [29]:
ranarr.argmax() # max value position in the array

7

In [30]:
ranarr.min() # min value in the array

1

In [31]:
ranarr.argmin() # min value position in the array

8

### another representation

In [32]:
from numpy.random import randint

In [33]:
randint(3, 100, 20)

array([19, 15, 19, 41, 82, 87, 68, 69, 79, 38, 14, 96,  3, 91, 98, 40, 68,
       43, 40, 85])

### Numpy indexing and selection

In [34]:
array1 = np.arange(0,25)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
array1[8]

8

In [36]:
array1[1:6]

array([1, 2, 3, 4, 5])

In [37]:
array1[:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
array1[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [39]:
array1[3:9] = 100

In [40]:
array1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [41]:
array2 = np.arange(40,75)
array2

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74])

In [42]:
slice_of_array2 = array2[4:19]
slice_of_array2

array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

In [43]:
slice_of_array2[:] = 0
slice_of_array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
array2

array([40, 41, 42, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74])

In [45]:
array3 = np.arange(100,125)
array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [46]:
copy_of_array3 = array3.copy()
copy_of_array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [47]:
copy_of_array3[5:11] = 0
copy_of_array3

array([100, 101, 102, 103, 104,   0,   0,   0,   0,   0,   0, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [48]:
array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

### 2d array

In [49]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
arr_2d[0]

array([1, 2, 3])

In [51]:
arr_2d[0][1]

2

In [52]:
arr_2d[2,1]

8

### 2D array slicing

In [53]:
arr_2d[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
arr_2d[1:3,1:]

array([[5, 6],
       [8, 9]])

In [55]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
array_2d = np.arange(0,50).reshape(5,10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
array_2d[:4, 3:7]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

### Boolean array and conditional array

In [58]:
bool_arr = array3 > 110
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [59]:
array3[bool_arr]

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124])

In [60]:
array3[array3 > 115]

array([116, 117, 118, 119, 120, 121, 122, 123, 124])

In [61]:
array3[array3 < 115]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114])