# NumPy

##### NumPy is a Linear Algebra Library for Python

# numpy arrays

In [1]:
import numpy as np

In [2]:
list_item = [1,2,3,4]
arr = np.array(list_item)
print(arr)

[1 2 3 4]


In [3]:
print(arr[2])

3


In [4]:
list_mat = [[1,2,3], [4,5,6], [7,8,9]]
np.array(list_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
mat = np.array(list_mat)

In [6]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### numpy range function (0-99) not including 100

In [7]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(0,100,5) # (start, end, stepsize)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((4,5)) # (rows, columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,100) # (start, end, evenly spaced points)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### one dimentional random samples from uniform distribution over 0 to 1

In [14]:
np.random.rand(5)

array([0.38718696, 0.02029212, 0.48815926, 0.27975631, 0.10254237])

### two dimentional random samples from uniform distribution over 0 to 1

In [15]:
np.random.rand(5,5)

array([[0.69201313, 0.87788905, 0.92479268, 0.68955311, 0.60334646],
       [0.91948017, 0.664193  , 0.36588945, 0.72183214, 0.09637979],
       [0.35755028, 0.05541379, 0.38031089, 0.40539304, 0.49939504],
       [0.83285427, 0.71208835, 0.07903301, 0.74917906, 0.94922468],
       [0.62297713, 0.34000585, 0.29490606, 0.75527522, 0.31503709]])

### random samples from standard normal distribution

In [16]:
np.random.randn(5)

array([ 0.48083278, -1.58956524,  0.13434344, -1.39283912, -0.09661821])

In [17]:
np.random.randn(6,5)

array([[ 1.38174157, -0.08941703,  0.74274854,  1.26611728, -3.14393671],
       [-1.03131975,  0.52131093, -0.6195072 ,  2.32608547, -1.25521504],
       [ 0.1511954 , -1.8104039 ,  0.27896409, -0.04474822, -0.07462953],
       [ 1.39240971,  0.15450258,  0.04561091,  0.34589986, -0.36066834],
       [ 1.04979901, -1.11356906,  1.80360695, -0.62311913, -0.45102932],
       [ 0.88450279,  1.85831812,  0.7492464 ,  0.05113104,  0.80327562]])

### generate random number

In [18]:
np.random.randint(1, 1000)

471

In [19]:
np.random.randint(1, 1000, 50) # (low, high, size)

array([964, 185, 779, 364, 819, 660, 768, 753, 127, 742, 543, 874, 215,
       874, 953, 792, 780, 225,  64, 541, 441, 632, 538, 149, 928, 621,
       208, 666, 821, 789, 333, 858, 178, 430, 518, 352, 661, 387, 976,
       739,  17, 987, 779, 776,  80, 194, 829, 483,  92, 601])

### reshape elements

In [20]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.shape # indicates one dimentional array

(25,)

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr1 = arr.reshape(5,5) # number of element must be equal to matrix
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr1.shape # indicates two dimentional array

(5, 5)

In [25]:
arr1.dtype

dtype('int32')

### find max and min value in an array

In [26]:
ranarr = np.random.randint(1,55, 10)
ranarr

array([26, 22, 32, 24,  7, 38, 44,  9, 25, 17])

In [27]:
ranarr.dtype

dtype('int32')

In [28]:
ranarr.max() # max value in the array

44

In [29]:
ranarr.argmax() # max value position in the array

6

In [30]:
ranarr.min() # min value in the array

7

In [31]:
ranarr.argmin() # min value position in the array

4

### another representation

In [32]:
from numpy.random import randint

In [33]:
randint(3, 100, 20)

array([46, 37, 21, 67, 34, 94, 59, 73, 62, 74, 20, 34, 31, 44, 18, 25, 84,
       91, 89, 45])

### Numpy indexing and selection

In [34]:
array1 = np.arange(0,25)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
array1[8]

8

In [36]:
array1[1:6]

array([1, 2, 3, 4, 5])

In [37]:
array1[:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
array1[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [39]:
array1[3:9] = 100

In [40]:
array1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [41]:
array2 = np.arange(40,75)
array2

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74])

In [42]:
slice_of_array2 = array2[4:19]
slice_of_array2

array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])

In [43]:
slice_of_array2[:] = 0
slice_of_array2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
array2

array([40, 41, 42, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74])

In [45]:
array3 = np.arange(100,125)
array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [46]:
copy_of_array3 = array3.copy()
copy_of_array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [47]:
copy_of_array3[5:11] = 0
copy_of_array3

array([100, 101, 102, 103, 104,   0,   0,   0,   0,   0,   0, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [48]:
array3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

### 2d array

In [49]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
arr_2d[0]

array([1, 2, 3])

In [51]:
arr_2d[0][1]

2

In [52]:
arr_2d[2,1]

8

### 2D array slicing

In [53]:
arr_2d[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [54]:
arr_2d[1:3,1:]

array([[5, 6],
       [8, 9]])

In [55]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
array_2d = np.arange(0,50).reshape(5,10)
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
array_2d[:4, 3:7]

array([[ 3,  4,  5,  6],
       [13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

### matrix sum, std

In [58]:
array_2d.sum()

1225

In [59]:
np.std(array_2d)

14.430869689661812

In [60]:
array_2d.std()

14.430869689661812

In [61]:
array_2d.sum(axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [62]:
array_2d.sum(axis=-1)

array([ 45, 145, 245, 345, 445])

### Boolean array and conditional array

In [63]:
bool_arr = array3 > 110
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [64]:
array3[bool_arr]

array([111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
       124])

In [65]:
array3[array3 > 115]

array([116, 117, 118, 119, 120, 121, 122, 123, 124])

In [66]:
array3[array3 < 115]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114])

## Numpy operations

### scalar operation

In [67]:
array3 + array3

array([200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224,
       226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248])

In [68]:
array3 - array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [69]:
array3 * array3

array([10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664,
       11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689,
       13924, 14161, 14400, 14641, 14884, 15129, 15376])

In [70]:
array3 - 100

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
(array3 - 100) / array3

array([0.        , 0.00990099, 0.01960784, 0.02912621, 0.03846154,
       0.04761905, 0.05660377, 0.06542056, 0.07407407, 0.08256881,
       0.09090909, 0.0990991 , 0.10714286, 0.11504425, 0.12280702,
       0.13043478, 0.13793103, 0.14529915, 0.15254237, 0.15966387,
       0.16666667, 0.17355372, 0.18032787, 0.18699187, 0.19354839])

### Getting error as 100/0=inf and 0/0 = nan

In [72]:
array3  / (array3 - 100)

C:\Users\ShAhiN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([         inf, 101.        ,  51.        ,  34.33333333,
        26.        ,  21.        ,  17.66666667,  15.28571429,
        13.5       ,  12.11111111,  11.        ,  10.09090909,
         9.33333333,   8.69230769,   8.14285714,   7.66666667,
         7.25      ,   6.88235294,   6.55555556,   6.26315789,
         6.        ,   5.76190476,   5.54545455,   5.34782609,
         5.16666667])

In [73]:
(array3 - 100)  / (array3 - 100)

C:\Users\ShAhiN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
array3 ** 2

array([10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664,
       11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689,
       13924, 14161, 14400, 14641, 14884, 15129, 15376], dtype=int32)

### some universal functions

In [75]:
np.sqrt(array3) 

array([10.        , 10.04987562, 10.09950494, 10.14889157, 10.19803903,
       10.24695077, 10.29563014, 10.34408043, 10.39230485, 10.44030651,
       10.48808848, 10.53565375, 10.58300524, 10.63014581, 10.67707825,
       10.72380529, 10.77032961, 10.81665383, 10.86278049, 10.90871211,
       10.95445115, 11.        , 11.04536102, 11.09053651, 11.13552873])

In [76]:
np.exp(array3)

array([2.68811714e+43, 7.30705998e+43, 1.98626484e+44, 5.39922761e+44,
       1.46766223e+45, 3.98951957e+45, 1.08446386e+46, 2.94787839e+46,
       8.01316426e+46, 2.17820388e+47, 5.92097203e+47, 1.60948707e+48,
       4.37503945e+48, 1.18925902e+49, 3.23274119e+49, 8.78750164e+49,
       2.38869060e+50, 6.49313426e+50, 1.76501689e+51, 4.79781333e+51,
       1.30418088e+52, 3.54513118e+52, 9.63666567e+52, 2.61951732e+53,
       7.12058633e+53])

In [77]:
np.log(array3)

array([4.60517019, 4.61512052, 4.62497281, 4.63472899, 4.6443909 ,
       4.65396035, 4.66343909, 4.67282883, 4.68213123, 4.69134788,
       4.70048037, 4.7095302 , 4.71849887, 4.72738782, 4.73619845,
       4.74493213, 4.75359019, 4.76217393, 4.77068462, 4.77912349,
       4.78749174, 4.79579055, 4.80402104, 4.81218436, 4.82028157])

In [78]:
np.max(array3)

124

In [79]:
np.min(array3)

100

In [80]:
array3.max()

124

In [81]:
np.sin(array3)

array([-0.50636564,  0.45202579,  0.99482679,  0.62298863, -0.3216224 ,
       -0.97053528, -0.7271425 ,  0.18478174,  0.92681851,  0.81674261,
       -0.04424268, -0.86455145, -0.8899956 , -0.09718191,  0.78498039,
        0.94543533,  0.23666139, -0.68969794, -0.98195217, -0.3714041 ,
        0.58061118,  0.99881522,  0.49871315, -0.45990349, -0.99568699])

In [82]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [83]:
np.linspace(0.01, 1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])