# NumPy

##### NumPy is a Linear Algebra Library for Python

# numpy arrays

In [1]:
import numpy as np

In [2]:
list_item = [1,2,3,4]
arr = np.array(list_item)
print(arr)

[1 2 3 4]


In [3]:
print(arr[2])

3


In [4]:
list_mat = [[1,2,3], [4,5,6], [7,8,9]]
np.array(list_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
mat = np.array(list_mat)

In [6]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### numpy range function (0-99) not including 100

In [7]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(0,100,5) # (start, end, stepsize)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((4,5)) # (rows, columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,100) # (start, end, evenly spaced points)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# identity matrix

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### one dimentional random samples from uniform distribution over 0 to 1

In [14]:
np.random.rand(5)

array([0.75934843, 0.05149272, 0.25353929, 0.24733523, 0.91300749])

### two dimentional random samples from uniform distribution over 0 to 1

In [15]:
np.random.rand(5,5)

array([[0.72178365, 0.89324795, 0.88306699, 0.7330428 , 0.58849648],
       [0.29377946, 0.27503607, 0.93186071, 0.61065909, 0.76488463],
       [0.3219929 , 0.56726811, 0.31098988, 0.52488295, 0.39157899],
       [0.53082479, 0.08802658, 0.87655049, 0.55394542, 0.09122118],
       [0.57213292, 0.00686319, 0.42095187, 0.00575445, 0.46238446]])

### random samples from standard normal distribution

In [16]:
np.random.randn(5)

array([-0.30033052, -0.97211436,  0.24743709,  2.01310667, -1.70230932])

In [17]:
np.random.randn(6,5)

array([[-0.33002005,  0.87747053, -0.40906168, -1.12998906, -0.31169524],
       [ 2.93297764, -0.44965353, -0.00340899,  0.74900814, -0.64598249],
       [-1.12025119,  1.05893001, -2.24411141,  1.54772337, -0.08227223],
       [ 1.30305925, -0.94181787, -0.49707122, -0.4557216 ,  0.86024288],
       [-1.24686313, -0.2481979 , -0.50091428,  1.06809858,  0.24402437],
       [-0.55983104, -0.65133   ,  0.10176534,  0.26050366,  1.09976999]])

### generate random number

In [18]:
np.random.randint(1, 1000)

449

In [19]:
np.random.randint(1, 1000, 50) # (low, high, size)

array([ 77, 704, 325, 650, 127, 260, 648, 240, 494, 873, 915, 782, 487,
       238, 988,  13, 825, 944,  19, 542, 102, 990, 143,  26, 885, 597,
        36, 450, 581, 408, 670, 956, 141, 717, 656, 784, 972,  46, 396,
       716, 914, 798,  17, 813, 818, 587, 437, 950,  56, 563])

### reshape elements

In [20]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr.shape # indicates one dimentional array

(25,)

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr1 = arr.reshape(5,5) # number of element must be equal to matrix
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr1.shape # indicates two dimentional array

(5, 5)

In [25]:
arr1.dtype

dtype('int32')

### find max and min value in an array

In [26]:
ranarr = np.random.randint(1,55, 10)
ranarr

array([34, 11, 22,  4, 21,  2, 18, 21, 48, 48])

In [27]:
ranarr.dtype

dtype('int32')

In [28]:
ranarr.max() # max value in the array

48

In [29]:
ranarr.argmax() # max value position in the array

8

In [30]:
ranarr.min() # min value in the array

2

In [31]:
ranarr.argmin() # min value position in the array

5

### another representation

In [32]:
from numpy.random import randint

In [33]:
randint(3, 100, 20)

array([31,  7, 42, 41, 51, 26, 65, 84, 21, 16, 73, 37, 14, 16, 10, 16, 72,
       27, 64, 58])